import numpy as np
vcoco_obj_text_label = [(0, 'a photo of a person and a person'), (1, 'a photo of a person and a bicycle'),
                        (2, 'a photo of a person and a car'), (3, 'a photo of a person and a motorcycle'),
                        (4, 'a photo of a person and an airplane'), (5, 'a photo of a person and a bus'),
                        (6, 'a photo of a person and a train'), (7, 'a photo of a person and a truck'),
                        (8, 'a photo of a person and a boat'), (9, 'a photo of a person and a traffic light'),
                        (10, 'a photo of a person and a fire hydrant'), (11, 'a photo of a person and a stop sign'),
                        (12, 'a photo of a person and a parking meter'), (13, 'a photo of a person and a bench'),
                        (14, 'a photo of a person and a bird'), (15, 'a photo of a person and a cat'),
                        (16, 'a photo of a person and a dog'), (17, 'a photo of a person and a horse'),
                        (18, 'a photo of a person and a sheep'), (19, 'a photo of a person and a cow'),
                        (20, 'a photo of a person and an elephant'), (21, 'a photo of a person and a bear'),
                        (22, 'a photo of a person and a zebra'), (23, 'a photo of a person and a giraffe'),
                        (24, 'a photo of a person and a backpack'), (25, 'a photo of a person and a umbrella'),
                        (26, 'a photo of a person and a handbag'), (27, 'a photo of a person and a tie'),
                        (28, 'a photo of a person and a suitcase'), (29, 'a photo of a person and a frisbee'),
                        (30, 'a photo of a person and a skis'), (31, 'a photo of a person and a snowboard'),
                        (32, 'a photo of a person and a sports ball'), (33, 'a photo of a person and a kite'),
                        (34, 'a photo of a person and a baseball bat'),
                        (35, 'a photo of a person and a baseball glove'),
                        (36, 'a photo of a person and a skateboard'), (37, 'a photo of a person and a surfboard'),
                        (38, 'a photo of a person and a tennis racket'), (39, 'a photo of a person and a bottle'),
                        (40, 'a photo of a person and a wine glass'), (41, 'a photo of a person and a cup'),
                        (42, 'a photo of a person and a fork'), (43, 'a photo of a person and a knife'),
                        (44, 'a photo of a person and a spoon'), (45, 'a photo of a person and a bowl'),
                        (46, 'a photo of a person and a banana'), (47, 'a photo of a person and an apple'),
                        (48, 'a photo of a person and a sandwich'), (49, 'a photo of a person and an orange'),
                        (50, 'a photo of a person and a broccoli'), (51, 'a photo of a person and a carrot'),
                        (52, 'a photo of a person and a hot dog'), (53, 'a photo of a person and a pizza'),
                        (54, 'a photo of a person and a donut'), (55, 'a photo of a person and a cake'),
                        (56, 'a photo of a person and a chair'), (57, 'a photo of a person and a couch'),
                        (58, 'a photo of a person and a potted plant'), (59, 'a photo of a person and a bed'),
                        (60, 'a photo of a person and a dining table'), (61, 'a photo of a person and a toilet'),
                        (62, 'a photo of a person and a tv'), (63, 'a photo of a person and a laptop'),
                        (64, 'a photo of a person and a mouse'), (65, 'a photo of a person and a remote'),
                        (66, 'a photo of a person and a keyboard'), (67, 'a photo of a person and a cell phone'),
                        (68, 'a photo of a person and a microwave'), (69, 'a photo of a person and an oven'),
                        (70, 'a photo of a person and a toaster'), (71, 'a photo of a person and a sink'),
                        (72, 'a photo of a person and a refrigerator'), (73, 'a photo of a person and a book'),
                        (74, 'a photo of a person and a clock'), (75, 'a photo of a person and a vase'),
                        (76, 'a photo of a person and a scissors'), (77, 'a photo of a person and a teddy bear'),
                        (78, 'a photo of a person and a hair drier'), (79, 'a photo of a person and a toothbrush'),
                        (80, 'a photo of a person only'), (81, 'a photo of nothing')]

UNSEEN_VERBS = [0,1,3,7,9,11,13,17,20,23]

OBJ_IDX_TO_OBJ_NAME = ['background', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat',
                'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse',
                'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
                'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove',
                'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
                'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
                'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse',
                'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book',
                'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']

ACT_IDX_TO_ACT_NAME = ['hold obj', 'sit instr', 'ride instr', 'look obj', 'hit instr', 'hit obj', 'eat obj', 'eat instr',
                      'jump instr', 'lay instr', 'talk_on_phone instr', 'carry obj', 'throw obj', 'catch obj',
                      'cut instr', 'cut obj', 'work_on_computer instr', 'ski instr', 'surf instr', 'skateboard instr',
                      'drink instr', 'kick obj', 'read obj', 'snowboard instr']

MAP_AO_TO_HOI = np.full([len(ACT_IDX_TO_ACT_NAME), len(OBJ_IDX_TO_OBJ_NAME)], 213)

# 213
vcoco_hoi_text_label = {(0, 42): 'a photo of a person holding a cup', (23, 0): 'a photo of a person hitting with something',
                        (14, 54): 'a photo of a person cutting a pizza', (0, 54): 'a photo of a person holding a pizza',
                        (1, 0): 'a photo of a person walking', (6, 54): 'a photo of a person eating a pizza',
                        (18, 38): 'a photo of a person jumping a surfboard', (0, 74): 'a photo of a person holding a book',
                        (1, 14): 'a photo of a person sitting a bench', (3, 74): 'a photo of a person looking at a book',
                        (22, 74): 'a photo of a person reading a book', (22, 0): 'a photo of a person reading',
                        (19, 37): 'a photo of a person carrying a skateboard', (17, 31): 'a photo of a person jumping a skis',
                        (0, 0): 'a photo of a person holding a person', (6, 0): 'a photo of a person eating',
                        (1, 57): 'a photo of a person sitting a chair', (3, 64): 'a photo of a person working on computer a laptop',
                        (0, 41): 'a photo of a person holding a wine glass', (20, 41): 'a photo of a person drinking a wine glass', (23, 32): 'a photo of a person carrying a snowboard', (0, 77): 'a photo of a person holding a scissors', (3, 0): 'a photo of a person talking on phone', (3, 77): 'a photo of a person looking at a scissors', (23, 77): 'a photo of a person cutting with a scissors', (14, 0): 'a photo of a person pointing a person', (1, 18): 'a photo of a person riding a horse', (3, 30): 'a photo of a person looking at a frisbee', (8, 0): 'a photo of a person jumping', (12, 30): 'a photo of a person throwing a frisbee', (12, 0): 'a photo of a person throwing', (3, 54): 'a photo of a person looking at a pizza', (0, 49): 'a photo of a person holding a sandwich', (6, 49): 'a photo of a person eating a sandwich', (0, 68): 'a photo of a person holding a cell phone', (0, 25): 'a photo of a person holding a backpack', (11, 25): 'a photo of a person carrying a backpack', (9, 0): 'a photo of a person laying', (9, 58): 'a photo of a person laying a couch', (0, 18): 'a photo of a person holding a horse', (0, 16): 'a photo of a person holding a cat', (9, 60): 'a photo of a person laying a bed', (13, 30): 'a photo of a person catching a frisbee', (13, 0): 'a photo of a person pointing', (13, 68): 'a photo of a person talking on phone a cell phone', (0, 80): 'a photo of a person holding a toothbrush', (0, 40): 'a photo of a person holding a bottle', (20, 40): 'a photo of a person drinking a bottle', (1, 60): 'a photo of a person sitting a bed', (3, 49): 'a photo of a person looking at a sandwich', (0, 39): 'a photo of a person holding a tennis racket', (3, 33): 'a photo of a person looking at a sports ball', (23, 39): 'a photo of a person hitting with a tennis racket', (4, 33): 'a photo of a person hitting a sports ball', (3, 18): 'a photo of a person looking at a horse', (0, 48): 'a photo of a person holding an apple', (3, 19): 'a photo of a person pointing a sheep', (6, 48): 'a photo of a person eating an apple', (21, 33): 'a photo of a person kicking a sports ball', (0, 45): 'a photo of a person holding a spoon', (3, 56): 'a photo of a person pointing a cake', (6, 56): 'a photo of a person eating a cake', (23, 45): 'a photo of a person eating with a spoon', (0, 64): 'a photo of a person holding a laptop', (1, 4): 'a photo of a person riding a motorcycle', (0, 44): 'a photo of a person holding a knife', (3, 44): 'a photo of a person looking at a knife', (23, 44): 'a photo of a person eating with a knife', (14, 56): 'a photo of a person cutting a cake', (4, 0): 'a photo of a person hitting', (0, 35): 'a photo of a person holding a baseball bat', (23, 35): 'a photo of a person hitting with a baseball bat', (13, 16): 'a photo of a person catching', (1, 58): 'a photo of a person sitting a couch', (0, 78): 'a photo of a person holding a teddy bear', (11, 50): 'a photo of a person carrying an orange', (0, 43): 'a photo of a person holding a fork', (23, 43): 'a photo of a person cutting with a fork', (3, 63): 'a photo of a person looking at a tv', (0, 29): 'a photo of a person holding a suitcase', (11, 29): 'a photo of a person carrying a suitcase', (1, 21): 'a photo of a person riding an elephant', (3, 16): 'a photo of a person looking at a cat', (0, 57): 'a photo of a person holding a chair', (3, 61): 'a photo of a person looking at a dining table', (20, 42): 'a photo of a person drinking a cup', (11, 27): 'a photo of a person carrying a handbag', (3, 17): 'a photo of a person looking at a dog', (0, 47): 'a photo of a person holding a banana', (11, 47): 'a photo of a person carrying a banana', (3, 29): 'a photo of a person looking at a suitcase', (6, 55): 'a photo of a person eating a donut', (0, 36): 'a photo of a person holding a baseball glove', (0, 66): 'a photo of a person holding a remote', (0, 55): 'a photo of a person holding a donut', (0, 27): 'a photo of a person holding a handbag', (11, 3): 'a photo of a person carrying a person', (0, 33): 'a photo of a person holding a sports ball', (12, 33): 'a photo of a person throwing a sports ball', (3, 55): 'a photo of a person looking at a donut', (0, 2): 'a photo of a person holding a bicycle', (1, 2): 'a photo of a person riding a bicycle', (3, 2): 'a photo of a person looking at a bicycle', (21, 0): 'a photo of a person kicking', (3, 68): 'a photo of a person looking at a cell phone', (3, 7): 'a photo of a person looking at a train', (0, 30): 'a photo of a person holding a frisbee', (19, 8): 'a photo of a person riding a truck', (19, 64): 'a photo of a person pointing a laptop', (0, 4): 'a photo of a person holding a motorcycle', (0, 26): 'a photo of a person holding a umbrella', (3, 46): 'a photo of a person looking at a bowl', (14, 52): 'a photo of a person cutting a carrot', (0, 53): 'a photo of a person holding a hot dog', (6, 53): 'a photo of a person eating a hot dog', (0, 34): 'a photo of a person pointing a kite', (3, 14): 'a photo of a person looking at a bench', (3, 36): 'a photo of a person looking at a baseball glove', (13, 33): 'a photo of a person catching a sports ball', (11, 26): 'a photo of a person carrying a umbrella', (3, 41): 'a photo of a person looking at a wine glass', (3, 34): 'a photo of a person looking at a kite', (11, 34): 'a photo of a person carrying a kite', (11, 7): 'a photo of a person riding a train', (3, 45): 'a photo of a person looking at a spoon', (0, 21): 'a photo of a person holding an elephant', (18, 0): 'a photo of a person surfing', (3, 21): 'a photo of a person looking at an elephant', (3, 9): 'a photo of a person riding a boat', (3, 24): 'a photo of a person looking at a giraffe', (11, 68): 'a photo of a person carrying a cell phone', (9, 57): 'a photo of a person laying a chair', (3, 20): 'a photo of a person pointing a cow', (3, 43): 'a photo of a person looking at a fork', (0, 56): 'a photo of a person holding a cake', (11, 33): 'a photo of a person carrying a sports ball', (19, 68): 'a photo of a person pointing a cell phone', (3, 53): 'a photo of a person looking at a hot dog', (6, 47): 'a photo of a person eating a banana', (17, 0): 'a photo of a person skiing', (0, 15): 'a photo of a person holding a bird', (9, 61): 'a photo of a person laying a dining table', (0, 17): 'a photo of a person holding a dog', (0, 73): 'a photo of a person holding a refrigerator', (3, 73): 'a photo of a person pointing a refrigerator', (3, 8): 'a photo of a person looking at a truck', (3, 42): 'a photo of a person looking at a cup', (1, 62): 'a photo of a person sitting a toilet', (20, 0): 'a photo of a person drinking', (0, 28): 'a photo of a person pointing a tie', (3, 28): 'a photo of a person looking at a tie', (14, 28): 'a photo of a person cutting a tie', (3, 11): 'a photo of a person pointing a fire hydrant', (9, 14): 'a photo of a person laying a bench', (14, 19): 'a photo of a person cutting a sheep', (0, 65): 'a photo of a person holding a mouse', (3, 65): 'a photo of a person looking at a mouse', (3, 67): 'a photo of a person pointing a keyboard', (3, 6): 'a photo of a person riding a bus', (3, 3): 'a photo of a person looking at a car', (3, 5): 'a photo of a person looking at an airplane', (3, 47): 'a photo of a person looking at a banana', (1, 29): 'a photo of a person sitting a suitcase', (11, 30): 'a photo of a person carrying a frisbee', (3, 27): 'a photo of a person looking at a handbag', (6, 51): 'a photo of a person eating a broccoli', (14, 47): 'a photo of a person cutting a banana', (0, 19): 'a photo of a person holding a sheep', (14, 49): 'a photo of a person cutting a sandwich', (3, 4): 'a photo of a person looking at a motorcycle', (3, 25): 'a photo of a person looking at a backpack', (0, 46): 'a photo of a person holding a bowl', (0, 50): 'a photo of a person holding an orange', (6, 50): 'a photo of a person eating an orange', (3, 35): 'a photo of a person looking at a baseball bat', (14, 55): 'a photo of a person cutting a donut', (3, 39): 'a photo of a person looking at a tennis racket', (6, 52): 'a photo of a person eating a carrot', (14, 48): 'a photo of a person cutting an apple', (11, 41): 'a photo of a person carrying a wine glass', (11, 49): 'a photo of a person pointing a sandwich', (11, 63): 'a photo of a person pointing a tv', (11, 75): 'a photo of a person carrying a clock', (3, 62): 'a photo of a person looking at a toilet', (3, 66): 'a photo of a person looking at a remote', (0, 51): 'a photo of a person holding a broccoli', (0, 14): 'a photo of a person holding a bench', (0, 8): 'a photo of a person holding a truck', (11, 42): 'a photo of a person carrying a cup', (20, 46): 'a photo of a person drinking a bowl', (11, 39): 'a photo of a person carrying a tennis racket', (11, 40): 'a photo of a person carrying a bottle', (3, 48): 'a photo of a person looking at an apple', (3, 57): 'a photo of a person looking at a chair', (1, 25): 'a photo of a person sitting a backpack', (1, 61): 'a photo of a person sitting a dining table', (0, 79): 'a photo of a person holding a hair drier', (3, 40): 'a photo of a person looking at a bottle', (3, 75): 'a photo of a person looking at a clock', (0, 9): 'a photo of a person holding a boat', (14, 46): 'a photo of a person cutting a bowl', (14, 24): 'a photo of a person pointing a giraffe', (3, 26): 'a photo of a person looking at a umbrella', (0, 67): 'a photo of a person holding a keyboard', (1, 27): 'a photo of a person sitting a handbag', (1, 53): 'a photo of a person pointing a hot dog', (11, 78): 'a photo of a person carrying a teddy bear', (0, 52): 'a photo of a person holding a carrot', (11, 35): 'a photo of a person carrying a baseball bat', (14, 51): 'a photo of a person cutting a broccoli', (3, 15): 'a photo of a person looking at a bird', (11, 74): 'a photo of a person carrying a book', (3, 51): 'a photo of a person looking at a broccoli'}
HOI_IDX_TO_OBJ_IDX = []
for idx, (key, hoi) in enumerate(vcoco_hoi_text_label.items()):
    MAP_AO_TO_HOI[key[0], key[1]] = idx
    HOI_IDX_TO_OBJ_IDX.append(key[0])    # 213
MAP_AO_TO_HOI.tolist()


vcoco_hoi_text_org_label = {(0, 41): 'a photo of a person holding a cup',
                        (16, 80): 'a photo of a person cutting with something',
                        (17, 53): 'a photo of a person cutting a pizza',
                        (0, 53): 'a photo of a person holding a pizza', (2, 80): 'a photo of a person sitting',
                        (8, 53): 'a photo of a person eating a pizza',
                        (9, 80): 'a photo of a person eating with something',
                        (23, 80): 'a photo of a person smiling', (21, 37): 'a photo of a person surfing a surfboard',
                        (0, 73): 'a photo of a person holding a book',
                        (2, 13): 'a photo of a person sitting a bench',
                        (5, 73): 'a photo of a person looking at a book',
                        (27, 73): 'a photo of a person reading a book', (1, 80): 'a photo of a person standing',
                        (22, 36): 'a photo of a person skateboarding a skateboard',
                        (20, 30): 'a photo of a person skiing a skis', (0, 80): 'a photo of a person holding',
                        (8, 80): 'a photo of a person eating', (2, 56): 'a photo of a person sitting a chair',
                        (5, 63): 'a photo of a person looking at a laptop',
                        (19, 63): 'a photo of a person working on computer a laptop',
                        (0, 40): 'a photo of a person holding a wine glass',
                        (24, 40): 'a photo of a person drinking a wine glass',
                        (5, 31): 'a photo of a person looking at a snowboard',
                        (28, 31): 'a photo of a person snowboarding a snowboard',
                        (0, 76): 'a photo of a person holding a scissors',
                        (5, 80): 'a photo of a person looking at something',
                        (5, 76): 'a photo of a person looking at a scissors',
                        (16, 76): 'a photo of a person cutting with a scissors',
                        (17, 80): 'a photo of a person cutting',
                        (5, 37): 'a photo of a person looking at a surfboard',
                        (2, 17): 'a photo of a person sitting a horse',
                        (3, 17): 'a photo of a person riding a horse', (4, 80): 'a photo of a person walking',
                        (5, 29): 'a photo of a person looking at a frisbee', (10, 80): 'a photo of a person jumping',
                        (14, 29): 'a photo of a person throwing a frisbee', (18, 80): 'a photo of a person running',
                        (5, 53): 'a photo of a person looking at a pizza',
                        (0, 48): 'a photo of a person holding a sandwich',
                        (8, 48): 'a photo of a person eating a sandwich',
                        (0, 67): 'a photo of a person holding a cell phone',
                        (19, 80): 'a photo of a person working on computer',
                        (0, 24): 'a photo of a person holding a backpack',
                        (13, 24): 'a photo of a person carrying a backpack', (11, 80): 'a photo of a person laying',
                        (11, 57): 'a photo of a person laying a couch',
                        (0, 17): 'a photo of a person holding a horse', (0, 15): 'a photo of a person holding a cat',
                        (11, 59): 'a photo of a person laying a bed',
                        (15, 29): 'a photo of a person catching a frisbee', (3, 80): 'a photo of a person riding',
                        (12, 67): 'a photo of a person talking on phone a cell phone',
                        (0, 31): 'a photo of a person holding a snowboard',
                        (10, 31): 'a photo of a person jumping a snowboard',
                        (5, 36): 'a photo of a person looking at a skateboard',
                        (10, 36): 'a photo of a person jumping a skateboard',
                        (0, 79): 'a photo of a person holding a toothbrush', (27, 80): 'a photo of a person reading',
                        (0, 39): 'a photo of a person holding a bottle',
                        (24, 39): 'a photo of a person drinking a bottle',
                        (2, 59): 'a photo of a person sitting a bed',
                        (5, 48): 'a photo of a person looking at a sandwich',
                        (0, 30): 'a photo of a person holding a skis',
                        (0, 38): 'a photo of a person holding a tennis racket',
                        (5, 32): 'a photo of a person looking at a sports ball',
                        (6, 38): 'a photo of a person hitting with a tennis racket',
                        (7, 32): 'a photo of a person hitting a sports ball',
                        (5, 0): 'a photo of a person looking at a person',
                        (5, 17): 'a photo of a person looking at a horse',
                        (0, 47): 'a photo of a person holding an apple',
                        (5, 18): 'a photo of a person looking at a sheep',
                        (8, 47): 'a photo of a person eating an apple',
                        (25, 32): 'a photo of a person kicking a sports ball',
                        (0, 44): 'a photo of a person holding a spoon',
                        (5, 55): 'a photo of a person looking at a cake',
                        (8, 55): 'a photo of a person eating a cake',
                        (9, 44): 'a photo of a person eating with a spoon',
                        (0, 63): 'a photo of a person holding a laptop',
                        (6, 80): 'a photo of a person hitting with something',
                        (2, 3): 'a photo of a person sitting a motorcycle',
                        (3, 3): 'a photo of a person riding a motorcycle',
                        (0, 43): 'a photo of a person holding a knife',
                        (5, 43): 'a photo of a person looking at a knife',
                        (16, 43): 'a photo of a person cutting with a knife',
                        (17, 55): 'a photo of a person cutting a cake', (7, 80): 'a photo of a person hitting',
                        (0, 34): 'a photo of a person holding a baseball bat',
                        (6, 34): 'a photo of a person hitting with a baseball bat',
                        (15, 80): 'a photo of a person catching', (2, 57): 'a photo of a person sitting a couch',
                        (0, 77): 'a photo of a person holding a teddy bear',
                        (13, 49): 'a photo of a person carrying an orange',
                        (0, 42): 'a photo of a person holding a fork',
                        (9, 42): 'a photo of a person eating with a fork',
                        (5, 62): 'a photo of a person looking at a tv',
                        (0, 28): 'a photo of a person holding a suitcase',
                        (13, 28): 'a photo of a person carrying a suitcase',
                        (2, 20): 'a photo of a person sitting an elephant',
                        (3, 20): 'a photo of a person riding an elephant',
                        (5, 15): 'a photo of a person looking at a cat',
                        (0, 56): 'a photo of a person holding a chair',
                        (5, 60): 'a photo of a person looking at a dining table',
                        (24, 41): 'a photo of a person drinking a cup', (14, 80): 'a photo of a person throwing',
                        (13, 26): 'a photo of a person carrying a handbag',
                        (5, 16): 'a photo of a person looking at a dog',
                        (0, 46): 'a photo of a person holding a banana',
                        (13, 46): 'a photo of a person carrying a banana',
                        (5, 28): 'a photo of a person looking at a suitcase',
                        (9, 43): 'a photo of a person eating with a knife',
                        (0, 37): 'a photo of a person holding a surfboard',
                        (13, 37): 'a photo of a person carrying a surfboard',
                        (8, 54): 'a photo of a person eating a donut',
                        (0, 0): 'a photo of a person holding a person',
                        (0, 35): 'a photo of a person holding a baseball glove',
                        (0, 65): 'a photo of a person holding a remote',
                        (0, 54): 'a photo of a person holding a donut',
                        (0, 26): 'a photo of a person holding a handbag', (13, 80): 'a photo of a person carrying',
                        (13, 0): 'a photo of a person carrying a person',
                        (0, 32): 'a photo of a person holding a sports ball',
                        (14, 32): 'a photo of a person throwing a sports ball',
                        (5, 54): 'a photo of a person looking at a donut',
                        (0, 1): 'a photo of a person holding a bicycle',
                        (2, 1): 'a photo of a person sitting a bicycle',
                        (3, 1): 'a photo of a person riding a bicycle',
                        (5, 1): 'a photo of a person looking at a bicycle', (25, 80): 'a photo of a person kicking',
                        (5, 67): 'a photo of a person looking at a cell phone',
                        (5, 6): 'a photo of a person looking at a train',
                        (0, 29): 'a photo of a person holding a frisbee',
                        (0, 36): 'a photo of a person holding a skateboard',
                        (3, 7): 'a photo of a person riding a truck',
                        (26, 63): 'a photo of a person pointing a laptop',
                        (0, 3): 'a photo of a person holding a motorcycle',
                        (13, 30): 'a photo of a person carrying a skis',
                        (0, 25): 'a photo of a person holding a umbrella',
                        (5, 45): 'a photo of a person looking at a bowl',
                        (17, 51): 'a photo of a person cutting a carrot',
                        (0, 52): 'a photo of a person holding a hot dog',
                        (8, 52): 'a photo of a person eating a hot dog',
                        (0, 33): 'a photo of a person holding a kite',
                        (5, 13): 'a photo of a person looking at a bench',
                        (12, 80): 'a photo of a person talking on phone',
                        (22, 80): 'a photo of a person skateboarding',
                        (5, 35): 'a photo of a person looking at a baseball glove',
                        (15, 32): 'a photo of a person catching a sports ball',
                        (26, 80): 'a photo of a person pointing',
                        (13, 25): 'a photo of a person carrying a umbrella',
                        (5, 40): 'a photo of a person looking at a wine glass',
                        (10, 37): 'a photo of a person jumping a surfboard',
                        (5, 33): 'a photo of a person looking at a kite',
                        (13, 33): 'a photo of a person carrying a kite',
                        (3, 6): 'a photo of a person riding a train',
                        (5, 44): 'a photo of a person looking at a spoon',
                        (0, 20): 'a photo of a person holding an elephant', (21, 80): 'a photo of a person surfing',
                        (5, 20): 'a photo of a person looking at an elephant',
                        (3, 8): 'a photo of a person riding a boat',
                        (5, 23): 'a photo of a person looking at a giraffe',
                        (13, 67): 'a photo of a person carrying a cell phone',
                        (11, 56): 'a photo of a person laying a chair',
                        (5, 19): 'a photo of a person looking at a cow',
                        (5, 42): 'a photo of a person looking at a fork',
                        (0, 55): 'a photo of a person holding a cake',
                        (13, 32): 'a photo of a person carrying a sports ball',
                        (5, 30): 'a photo of a person looking at a skis',
                        (13, 36): 'a photo of a person carrying a skateboard',
                        (26, 67): 'a photo of a person pointing a cell phone',
                        (5, 52): 'a photo of a person looking at a hot dog',
                        (8, 46): 'a photo of a person eating a banana', (20, 80): 'a photo of a person skiing',
                        (28, 80): 'a photo of a person snowboarding', (0, 14): 'a photo of a person holding a bird',
                        (11, 60): 'a photo of a person laying a dining table',
                        (0, 16): 'a photo of a person holding a dog',
                        (0, 72): 'a photo of a person holding a refrigerator',
                        (5, 72): 'a photo of a person looking at a refrigerator',
                        (5, 7): 'a photo of a person looking at a truck',
                        (5, 41): 'a photo of a person looking at a cup',
                        (2, 61): 'a photo of a person sitting a toilet', (24, 80): 'a photo of a person drinking',
                        (0, 27): 'a photo of a person holding a tie',
                        (5, 27): 'a photo of a person looking at a tie',
                        (17, 27): 'a photo of a person cutting a tie',
                        (5, 10): 'a photo of a person looking at a fire hydrant',
                        (26, 10): 'a photo of a person pointing a fire hydrant',
                        (11, 13): 'a photo of a person laying a bench',
                        (17, 18): 'a photo of a person cutting a sheep',
                        (0, 64): 'a photo of a person holding a mouse',
                        (5, 64): 'a photo of a person looking at a mouse',
                        (5, 66): 'a photo of a person looking at a keyboard',
                        (16, 42): 'a photo of a person cutting with a fork',
                        (17, 0): 'a photo of a person cutting a person',
                        (5, 5): 'a photo of a person looking at a bus', (3, 2): 'a photo of a person riding a car',
                        (10, 30): 'a photo of a person jumping a skis',
                        (5, 4): 'a photo of a person looking at an airplane',
                        (5, 46): 'a photo of a person looking at a banana',
                        (2, 28): 'a photo of a person sitting a suitcase',
                        (13, 29): 'a photo of a person carrying a frisbee',
                        (5, 26): 'a photo of a person looking at a handbag',
                        (8, 50): 'a photo of a person eating a broccoli',
                        (17, 46): 'a photo of a person cutting a banana',
                        (0, 18): 'a photo of a person holding a sheep',
                        (17, 48): 'a photo of a person cutting a sandwich',
                        (26, 0): 'a photo of a person pointing a person',
                        (5, 3): 'a photo of a person looking at a motorcycle',
                        (5, 24): 'a photo of a person looking at a backpack',
                        (0, 45): 'a photo of a person holding a bowl',
                        (26, 27): 'a photo of a person pointing a tie',
                        (0, 49): 'a photo of a person holding an orange',
                        (8, 49): 'a photo of a person eating an orange',
                        (5, 34): 'a photo of a person looking at a baseball bat',
                        (13, 31): 'a photo of a person carrying a snowboard',
                        (17, 54): 'a photo of a person cutting a donut',
                        (5, 38): 'a photo of a person looking at a tennis racket',
                        (8, 51): 'a photo of a person eating a carrot',
                        (17, 47): 'a photo of a person cutting an apple',
                        (13, 40): 'a photo of a person carrying a wine glass',
                        (26, 48): 'a photo of a person pointing a sandwich',
                        (26, 62): 'a photo of a person pointing a tv',
                        (13, 74): 'a photo of a person carrying a clock',
                        (5, 61): 'a photo of a person looking at a toilet',
                        (26, 19): 'a photo of a person pointing a cow',
                        (5, 65): 'a photo of a person looking at a remote',
                        (26, 18): 'a photo of a person pointing a sheep',
                        (0, 50): 'a photo of a person holding a broccoli',
                        (0, 13): 'a photo of a person holding a bench',
                        (26, 33): 'a photo of a person pointing a kite',
                        (0, 7): 'a photo of a person holding a truck',
                        (13, 41): 'a photo of a person carrying a cup',
                        (24, 45): 'a photo of a person drinking a bowl',
                        (13, 38): 'a photo of a person carrying a tennis racket',
                        (13, 39): 'a photo of a person carrying a bottle',
                        (5, 47): 'a photo of a person looking at an apple',
                        (5, 56): 'a photo of a person looking at a chair',
                        (2, 24): 'a photo of a person sitting a backpack',
                        (26, 60): 'a photo of a person pointing a dining table',
                        (0, 78): 'a photo of a person holding a hair drier',
                        (5, 39): 'a photo of a person looking at a bottle',
                        (26, 55): 'a photo of a person pointing a cake',
                        (26, 66): 'a photo of a person pointing a keyboard',
                        (26, 72): 'a photo of a person pointing a refrigerator',
                        (5, 74): 'a photo of a person looking at a clock',
                        (0, 8): 'a photo of a person holding a boat', (17, 45): 'a photo of a person cutting a bowl',
                        (26, 23): 'a photo of a person pointing a giraffe',
                        (5, 25): 'a photo of a person looking at a umbrella',
                        (0, 66): 'a photo of a person holding a keyboard',
                        (2, 26): 'a photo of a person sitting a handbag',
                        (26, 52): 'a photo of a person pointing a hot dog',
                        (2, 60): 'a photo of a person sitting a dining table',
                        (13, 77): 'a photo of a person carrying a teddy bear',
                        (0, 51): 'a photo of a person holding a carrot',
                        (13, 34): 'a photo of a person carrying a baseball bat',
                        (5, 2): 'a photo of a person looking at a car', (3, 5): 'a photo of a person riding a bus',
                        (17, 50): 'a photo of a person cutting a broccoli',
                        (5, 14): 'a photo of a person looking at a bird',
                        (13, 73): 'a photo of a person carrying a book',
                        (5, 50): 'a photo of a person looking at a broccoli'}
#
# {(0, 41): 'a photo of a person holding a cup',
#                         (16, 80): 'a photo of a person cutting with something',
#                         (17, 53): 'a photo of a person cutting a pizza',
#                         (0, 53): 'a photo of a person holding a pizza', (2, 80): 'a photo of a person sitting',
#                         (8, 53): 'a photo of a person eating a pizza',
#                         (9, 80): 'a photo of a person eating with something',
#                         (23, 80): 'a photo of a person smiling', (21, 37): 'a photo of a person surfing a surfboard',
#                         (0, 73): 'a photo of a person holding a book',
#                         (2, 13): 'a photo of a person sitting a bench',
#                         (5, 73): 'a photo of a person looking at a book',
#                         (27, 73): 'a photo of a person reading a book', (1, 80): 'a photo of a person standing',
#                         (22, 36): 'a photo of a person skateboarding a skateboard',
#                         (20, 30): 'a photo of a person skiing a skis', (0, 80): 'a photo of a person holding',
#                         (8, 80): 'a photo of a person eating', (2, 56): 'a photo of a person sitting a chair',
#                         (5, 63): 'a photo of a person looking at a laptop',
#                         (19, 63): 'a photo of a person working on computer a laptop',
#                         (0, 40): 'a photo of a person holding a wine glass',
#                         (24, 40): 'a photo of a person drinking a wine glass',
#                         (5, 31): 'a photo of a person looking at a snowboard',
#                         (28, 31): 'a photo of a person snowboarding a snowboard',
#                         (0, 76): 'a photo of a person holding a scissors',
#                         (5, 80): 'a photo of a person looking at something',
#                         (5, 76): 'a photo of a person looking at a scissors',
#                         (16, 76): 'a photo of a person cutting with a scissors',
#                         (17, 80): 'a photo of a person cutting',
#                         (5, 37): 'a photo of a person looking at a surfboard',
#                         (2, 17): 'a photo of a person sitting a horse',
#                         (3, 17): 'a photo of a person riding a horse', (4, 80): 'a photo of a person walking',
#                         (5, 29): 'a photo of a person looking at a frisbee', (10, 80): 'a photo of a person jumping',
#                         (14, 29): 'a photo of a person throwing a frisbee', (18, 80): 'a photo of a person running',
#                         (5, 53): 'a photo of a person looking at a pizza',
#                         (0, 48): 'a photo of a person holding a sandwich',
#                         (8, 48): 'a photo of a person eating a sandwich',
#                         (0, 67): 'a photo of a person holding a cell phone',
#                         (19, 80): 'a photo of a person working on computer',
#                         (0, 24): 'a photo of a person holding a backpack',
#                         (13, 24): 'a photo of a person carrying a backpack', (11, 80): 'a photo of a person laying',
#                         (11, 57): 'a photo of a person laying a couch',
#                         (0, 17): 'a photo of a person holding a horse', (0, 15): 'a photo of a person holding a cat',
#                         (11, 59): 'a photo of a person laying a bed',
#                         (15, 29): 'a photo of a person catching a frisbee', (3, 80): 'a photo of a person riding',
#                         (12, 67): 'a photo of a person talking on phone a cell phone',
#                         (0, 31): 'a photo of a person holding a snowboard',
#                         (10, 31): 'a photo of a person jumping a snowboard',
#                         (5, 36): 'a photo of a person looking at a skateboard',
#                         (10, 36): 'a photo of a person jumping a skateboard',
#                         (0, 79): 'a photo of a person holding a toothbrush', (27, 80): 'a photo of a person reading',
#                         (0, 39): 'a photo of a person holding a bottle',
#                         (24, 39): 'a photo of a person drinking a bottle',
#                         (2, 59): 'a photo of a person sitting a bed',
#                         (5, 48): 'a photo of a person looking at a sandwich',
#                         (0, 30): 'a photo of a person holding a skis',
#                         (0, 38): 'a photo of a person holding a tennis racket',
#                         (5, 32): 'a photo of a person looking at a sports ball',
#                         (6, 38): 'a photo of a person hitting with a tennis racket',
#                         (7, 32): 'a photo of a person hitting a sports ball',
#                         (5, 0): 'a photo of a person looking at a person',
#                         (5, 17): 'a photo of a person looking at a horse',
#                         (0, 47): 'a photo of a person holding an apple',
#                         (5, 18): 'a photo of a person looking at a sheep',
#                         (8, 47): 'a photo of a person eating an apple',
#                         (25, 32): 'a photo of a person kicking a sports ball',
#                         (0, 44): 'a photo of a person holding a spoon',
#                         (5, 55): 'a photo of a person looking at a cake',
#                         (8, 55): 'a photo of a person eating a cake',
#                         (9, 44): 'a photo of a person eating with a spoon',
#                         (0, 63): 'a photo of a person holding a laptop',
#                         (6, 80): 'a photo of a person hitting with something',
#                         (2, 3): 'a photo of a person sitting a motorcycle',
#                         (3, 3): 'a photo of a person riding a motorcycle',
#                         (0, 43): 'a photo of a person holding a knife',
#                         (5, 43): 'a photo of a person looking at a knife',
#                         (16, 43): 'a photo of a person cutting with a knife',
#                         (17, 55): 'a photo of a person cutting a cake', (7, 80): 'a photo of a person hitting',
#                         (0, 34): 'a photo of a person holding a baseball bat',
#                         (6, 34): 'a photo of a person hitting with a baseball bat',
#                         (15, 80): 'a photo of a person catching', (2, 57): 'a photo of a person sitting a couch',
#                         (0, 77): 'a photo of a person holding a teddy bear',
#                         (13, 49): 'a photo of a person carrying an orange',
#                         (0, 42): 'a photo of a person holding a fork',
#                         (9, 42): 'a photo of a person eating with a fork',
#                         (5, 62): 'a photo of a person looking at a tv',
#                         (0, 28): 'a photo of a person holding a suitcase',
#                         (13, 28): 'a photo of a person carrying a suitcase',
#                         (2, 20): 'a photo of a person sitting an elephant',
#                         (3, 20): 'a photo of a person riding an elephant',
#                         (5, 15): 'a photo of a person looking at a cat',
#                         (0, 56): 'a photo of a person holding a chair',
#                         (5, 60): 'a photo of a person looking at a dining table',
#                         (24, 41): 'a photo of a person drinking a cup', (14, 80): 'a photo of a person throwing',
#                         (13, 26): 'a photo of a person carrying a handbag',
#                         (5, 16): 'a photo of a person looking at a dog',
#                         (0, 46): 'a photo of a person holding a banana',
#                         (13, 46): 'a photo of a person carrying a banana',
#                         (5, 28): 'a photo of a person looking at a suitcase',
#                         (9, 43): 'a photo of a person eating with a knife',
#                         (0, 37): 'a photo of a person holding a surfboard',
#                         (13, 37): 'a photo of a person carrying a surfboard',
#                         (8, 54): 'a photo of a person eating a donut',
#                         (0, 0): 'a photo of a person holding a person',
#                         (0, 35): 'a photo of a person holding a baseball glove',
#                         (0, 65): 'a photo of a person holding a remote',
#                         (0, 54): 'a photo of a person holding a donut',
#                         (0, 26): 'a photo of a person holding a handbag', (13, 80): 'a photo of a person carrying',
#                         (13, 0): 'a photo of a person carrying a person',
#                         (0, 32): 'a photo of a person holding a sports ball',
#                         (14, 32): 'a photo of a person throwing a sports ball',
#                         (5, 54): 'a photo of a person looking at a donut',
#                         (0, 1): 'a photo of a person holding a bicycle',
#                         (2, 1): 'a photo of a person sitting a bicycle',
#                         (3, 1): 'a photo of a person riding a bicycle',
#                         (5, 1): 'a photo of a person looking at a bicycle', (25, 80): 'a photo of a person kicking',
#                         (5, 67): 'a photo of a person looking at a cell phone',
#                         (5, 6): 'a photo of a person looking at a train',
#                         (0, 29): 'a photo of a person holding a frisbee',
#                         (0, 36): 'a photo of a person holding a skateboard',
#                         (3, 7): 'a photo of a person riding a truck',
#                         (26, 63): 'a photo of a person pointing a laptop',
#                         (0, 3): 'a photo of a person holding a motorcycle',
#                         (13, 30): 'a photo of a person carrying a skis',
#                         (0, 25): 'a photo of a person holding a umbrella',
#                         (5, 45): 'a photo of a person looking at a bowl',
#                         (17, 51): 'a photo of a person cutting a carrot',
#                         (0, 52): 'a photo of a person holding a hot dog',
#                         (8, 52): 'a photo of a person eating a hot dog',
#                         (0, 33): 'a photo of a person holding a kite',
#                         (5, 13): 'a photo of a person looking at a bench',
#                         (12, 80): 'a photo of a person talking on phone',
#                         (22, 80): 'a photo of a person skateboarding',
#                         (5, 35): 'a photo of a person looking at a baseball glove',
#                         (15, 32): 'a photo of a person catching a sports ball',
#                         (26, 80): 'a photo of a person pointing',
#                         (13, 25): 'a photo of a person carrying a umbrella',
#                         (5, 40): 'a photo of a person looking at a wine glass',
#                         (10, 37): 'a photo of a person jumping a surfboard',
#                         (5, 33): 'a photo of a person looking at a kite',
#                         (13, 33): 'a photo of a person carrying a kite',
#                         (3, 6): 'a photo of a person riding a train',
#                         (5, 44): 'a photo of a person looking at a spoon',
#                         (0, 20): 'a photo of a person holding an elephant', (21, 80): 'a photo of a person surfing',
#                         (5, 20): 'a photo of a person looking at an elephant',
#                         (3, 8): 'a photo of a person riding a boat',
#                         (5, 23): 'a photo of a person looking at a giraffe',
#                         (13, 67): 'a photo of a person carrying a cell phone',
#                         (11, 56): 'a photo of a person laying a chair',
#                         (5, 19): 'a photo of a person looking at a cow',
#                         (5, 42): 'a photo of a person looking at a fork',
#                         (0, 55): 'a photo of a person holding a cake',
#                         (13, 32): 'a photo of a person carrying a sports ball',
#                         (5, 30): 'a photo of a person looking at a skis',
#                         (13, 36): 'a photo of a person carrying a skateboard',
#                         (26, 67): 'a photo of a person pointing a cell phone',
#                         (5, 52): 'a photo of a person looking at a hot dog',
#                         (8, 46): 'a photo of a person eating a banana', (20, 80): 'a photo of a person skiing',
#                         (28, 80): 'a photo of a person snowboarding', (0, 14): 'a photo of a person holding a bird',
#                         (11, 60): 'a photo of a person laying a dining table',
#                         (0, 16): 'a photo of a person holding a dog',
#                         (0, 72): 'a photo of a person holding a refrigerator',
#                         (5, 72): 'a photo of a person looking at a refrigerator',
#                         (5, 7): 'a photo of a person looking at a truck',
#                         (5, 41): 'a photo of a person looking at a cup',
#                         (2, 61): 'a photo of a person sitting a toilet', (24, 80): 'a photo of a person drinking',
#                         (0, 27): 'a photo of a person holding a tie',
#                         (5, 27): 'a photo of a person looking at a tie',
#                         (17, 27): 'a photo of a person cutting a tie',
#                         (5, 10): 'a photo of a person looking at a fire hydrant',
#                         (26, 10): 'a photo of a person pointing a fire hydrant',
#                         (11, 13): 'a photo of a person laying a bench',
#                         (17, 18): 'a photo of a person cutting a sheep',
#                         (0, 64): 'a photo of a person holding a mouse',
#                         (5, 64): 'a photo of a person looking at a mouse',
#                         (5, 66): 'a photo of a person looking at a keyboard',
#                         (16, 42): 'a photo of a person cutting with a fork',
#                         (17, 0): 'a photo of a person cutting a person',
#                         (5, 5): 'a photo of a person looking at a bus', (3, 2): 'a photo of a person riding a car',
#                         (10, 30): 'a photo of a person jumping a skis',
#                         (5, 4): 'a photo of a person looking at an airplane',
#                         (5, 46): 'a photo of a person looking at a banana',
#                         (2, 28): 'a photo of a person sitting a suitcase',
#                         (13, 29): 'a photo of a person carrying a frisbee',
#                         (5, 26): 'a photo of a person looking at a handbag',
#                         (8, 50): 'a photo of a person eating a broccoli',
#                         (17, 46): 'a photo of a person cutting a banana',
#                         (0, 18): 'a photo of a person holding a sheep',
#                         (17, 48): 'a photo of a person cutting a sandwich',
#                         (26, 0): 'a photo of a person pointing a person',
#                         (5, 3): 'a photo of a person looking at a motorcycle',
#                         (5, 24): 'a photo of a person looking at a backpack',
#                         (0, 45): 'a photo of a person holding a bowl',
#                         (26, 27): 'a photo of a person pointing a tie',
#                         (0, 49): 'a photo of a person holding an orange',
#                         (8, 49): 'a photo of a person eating an orange',
#                         (5, 34): 'a photo of a person looking at a baseball bat',
#                         (13, 31): 'a photo of a person carrying a snowboard',
#                         (17, 54): 'a photo of a person cutting a donut',
#                         (5, 38): 'a photo of a person looking at a tennis racket',
#                         (8, 51): 'a photo of a person eating a carrot',
#                         (17, 47): 'a photo of a person cutting an apple',
#                         (13, 40): 'a photo of a person carrying a wine glass',
#                         (26, 48): 'a photo of a person pointing a sandwich',
#                         (26, 62): 'a photo of a person pointing a tv',
#                         (13, 74): 'a photo of a person carrying a clock',
#                         (5, 61): 'a photo of a person looking at a toilet',
#                         (26, 19): 'a photo of a person pointing a cow',
#                         (5, 65): 'a photo of a person looking at a remote',
#                         (26, 18): 'a photo of a person pointing a sheep',
#                         (0, 50): 'a photo of a person holding a broccoli',
#                         (0, 13): 'a photo of a person holding a bench',
#                         (26, 33): 'a photo of a person pointing a kite',
#                         (0, 7): 'a photo of a person holding a truck',
#                         (13, 41): 'a photo of a person carrying a cup',
#                         (24, 45): 'a photo of a person drinking a bowl',
#                         (13, 38): 'a photo of a person carrying a tennis racket',
#                         (13, 39): 'a photo of a person carrying a bottle',
#                         (5, 47): 'a photo of a person looking at an apple',
#                         (5, 56): 'a photo of a person looking at a chair',
#                         (2, 24): 'a photo of a person sitting a backpack',
#                         (26, 60): 'a photo of a person pointing a dining table',
#                         (0, 78): 'a photo of a person holding a hair drier',
#                         (5, 39): 'a photo of a person looking at a bottle',
#                         (26, 55): 'a photo of a person pointing a cake',
#                         (26, 66): 'a photo of a person pointing a keyboard',
#                         (26, 72): 'a photo of a person pointing a refrigerator',
#                         (5, 74): 'a photo of a person looking at a clock',
#                         (0, 8): 'a photo of a person holding a boat', (17, 45): 'a photo of a person cutting a bowl',
#                         (26, 23): 'a photo of a person pointing a giraffe',
#                         (5, 25): 'a photo of a person looking at a umbrella',
#                         (0, 66): 'a photo of a person holding a keyboard',
#                         (2, 26): 'a photo of a person sitting a handbag',
#                         (26, 52): 'a photo of a person pointing a hot dog',
#                         (2, 60): 'a photo of a person sitting a dining table',
#                         (13, 77): 'a photo of a person carrying a teddy bear',
#                         (0, 51): 'a photo of a person holding a carrot',
#                         (13, 34): 'a photo of a person carrying a baseball bat',
#                         (5, 2): 'a photo of a person looking at a car', (3, 5): 'a photo of a person riding a bus',
#                         (17, 50): 'a photo of a person cutting a broccoli',
#                         (5, 14): 'a photo of a person looking at a bird',
#                         (13, 73): 'a photo of a person carrying a book',
#                         (5, 50): 'a photo of a person looking at a broccoli'}

